INSERT INTO `PREFIX_advcheckout_lang` (`id_field`, `id_lang`, `description`, `tooltip`) VALUES
(1, ID_LANG, 'Nombre', 'Tu nombre.'),
(2, ID_LANG, 'Apellido', 'Tu apellido.'),
(3, ID_LANG, 'Empresa', 'el Nombre de la empresa.'),
(4, ID_LANG, 'Contraseña', 'Adivine la contraseña (minutos 5 caracteres).'),
(5, ID_LANG, 'Su dirección de','Su dirección de'),
(6, ID_LANG, 'Su dirección de 2', 'la Secuela de la dirección.'),
(7, ID_LANG, 'E-mail', 'Tu E-mail.'),
(8, ID_LANG, 'Postal', 'Su código postal.'),
(9, ID_LANG, 'Ciudad', 'la Ciudad de la entrega.'),
(10, ID_LANG, 'País', 'el País de entrega.'),
(11, ID_LANG, 'Barrio', 'la Región de la entrega.'),
(12, ID_LANG, 'Otros', 'Más información.'),
(13, ID_LANG, 'Alias', 'el Nombre de la dirección.'),
(14, ID_LANG, 'la Casa. Teléfono', 'teléfono de la Casa +x xxx xxx-xx-xx'),
(15, ID_LANG, 'Mob. De los cuerpos', 'teléfono Móvil +x xxx xxx-xx-xx'),
(16, ID_LANG, 'DNI', 'DNI'),
(17, ID_LANG, 'Impuesto. La habitación', 'número de identificación Fiscal.'),
(18, ID_LANG, 'Suscribirse.', 'La suscripción al boletín informativo.'),
(19, ID_LANG, 'Recibir ofertas especiales de nuestros socios', 'Recibir ofertas especiales de nuestros socios'),
(20, ID_LANG, 'cumpleaños', 'cumpleaños'),
(21, ID_LANG, 'Paul', 'Sexo');