INSERT INTO `PREFIX_advcheckout_lang` (`id_field`, `id_lang`, `description`, `tooltip`) VALUES
(1, ID_LANG, 'nome', 'il tuo nome.'),
(2, ID_LANG, 'cognome', 'il vostro ultimo nome.'),
(3, ID_LANG, 'società', 'il vostro nome di azienda.'),
(4, ID_LANG,'La password', 'La password.'),
(5, ID_LANG, 'Indirizzo', 'il vostro vettore indirizzo.'),
(6, ID_LANG, 'Indirizzo (riga 2)', 'indirizzo estende.'),
(7, ID_LANG, 'E-mail', 'il vostro indirizzo E-mail.'),
(8, ID_LANG, 'Codice postale', 'Codice postale.'),
(9, ID_LANG, 'Città', 'il vostro vettore città.'),
(10, ID_LANG, 'paese', 'il vostro vettore paese.'),
(11, ID_LANG, 'stato', 'il vostro stato di portatore.'),
(12, ID_LANG, 'Maggiori informazioni', 'altre informazioni.'),
(13, ID_LANG, 'Nome indirizzo.', 'Dai un titolo a questo indirizzo per riferimenti futuri.'),
(14, ID_LANG, 'telefono', 'telefono di casa.'),
(15, ID_LANG, 'cellulare', 'cellulare.'),
(16, ID_LANG, 'identità', 'identità.'),
(17, ID_LANG, 'partita iva', 'il numero di partita iva.'),
(18, ID_LANG, 'Mandami notizie', 'Mandami notizie'),
(19, ID_LANG, 'invio di offerte', 'invio di offerte'),
(20, ID_LANG, 'compleanno', 'compleanno'),
(21, ID_LANG, 'sesso', 'sesso');