INSERT INTO `PREFIX_advcheckout_lang` (`id_field`, `id_lang`, `description`, `tooltip`) VALUES
(1, ID_LANG, 'Vardas', 'Jūsų vardas'),
(2, ID_LANG, 'Pavardė', 'Jūsų pavardė'),
(3, ID_LANG, 'company', 'yours company name.'),
(4, ID_LANG, 'Slaptažodis', 'Jūsų pasirinktas slaptažodis'),
(5, ID_LANG, 'Adresas', 'Jūsų tikslus adresas'),
(6, ID_LANG, 'address 2', 'address extends.'),
(7, ID_LANG, 'El. paštas', 'Jūsų el. pašto adresas'),
(8, ID_LANG, 'postcode', 'postcode.'),
(9, ID_LANG, 'Miestas', 'Jūsų miestas'),
(10, ID_LANG, 'country', 'yours carrier country.'),
(11, ID_LANG, 'state', 'yours carrier state.'),
(12, ID_LANG, 'other', 'other informations.'),
(13, ID_LANG, 'alias', 'alias.'),
(14, ID_LANG, 'phone', 'home phone.'),
(15, ID_LANG, 'Telefono numeris', 'Jūsų telefono numeris'),
(16, ID_LANG, 'dni', 'dni.'),
(17, ID_LANG, 'vat number', 'vat number.'),
(18, ID_LANG, 'Prenumeruokite mūsų naujienlaiškį!', 'Prenumeruokite mūsų naujienlaiškį!'),
(19, ID_LANG, 'send me offers', 'send me offers'),
(20, ID_LANG, 'birthday', 'birthday'),
(21, ID_LANG, 'gender', 'gender');