INSERT INTO `PREFIX_advcheckout_lang` (`id_field`, `id_lang`, `description`, `tooltip`) VALUES
(1, ID_LANG, 'förnamn', 'din första namn.'),
(2, ID_LANG, 'efternamn', 'ditt efternamn.'),
(3, ID_LANG, 'företag', 'ditt företags namn.'),
(4, ID_LANG, 'password', 'lösenord'),
(5, ID_LANG, 'adress', 'din transportör adress.'),
(6, ID_LANG, 'adress 2', ' adress sträcker sig.'),
(7, ID_LANG, 'E-post', 'din E-post.'),
(8, ID_LANG, 'postnr', 'postnummer.'),
(9, ID_LANG, 'stad', 'din transportör staden.'),
(10, ID_LANG, 'land', 'din transportör land.'),
(11, ID_LANG, 'tillstånd', 'din transportör staten.'),
(12, ID_LANG, 'andra', ' andra informationer.'),
(13, ID_LANG, 'alias', ' alias.'),
(14, ID_LANG, 'telefon', 'hem telefonen.'),
(15, ID_LANG, 'mobiltelefon', ' mobiltelefon.'),
(16, ID_LANG, 'dni', 'dni.'),
(17, ID_LANG, 'vat-nummer', 'vat-nummer.'),
(18, ID_LANG, 'nyhetsbrev', 'nyhetsbrev'),
(19, ID_LANG, ' skicka mig har', 'skicka mig har'),
(20, ID_LANG, 'födelsedag', 'födelsedag'),
(21, ID_LANG, 'kön', 'kön');